### ISSUE TITLE
If the hollow knight is defeated without having focus, the game enters a deadlock

### ISSUE THREAD

**Issue by decordoba** [homothetyhk/RandomizerMod#13]
I got 3 dreamers before finding focus, so I fought HK and won, then the game expects you to focus (press A) to absorb the infection.
But focus does not work therefore the fight cannot be finished.
The problem is that the game does not allow you to open the pause menu to quit or warp back to a bench, because you are at the end of the fight, so there is no way to defeat the boss or leave the fight.

I think this should be fixed, the only way to go back to a bench right now is to force-quit the game.

**Comment by homothetyhk** [comment]
Closed by [f6ac2f6](https://github.com/homothetyhk/HollowKnight.ItemChanger/commit/f6ac2f623196ad0bf643c6d3a561e4da5fdb6f0d).
