### ISSUE TITLE
White_Palace_05 transition logic

### ISSUE THREAD

**Issue by dewiniaid** [homothetyhk/RandomizerMod#14]
So, yesterday, [I visited this apparently out-of-logic soul totem](https://clips.twitch.tv/SuccessfulVictoriousPhoneChefFrank-WRIXzH5xgRIE6QT_) (Soul_Totem-White_Palace_Right) in White Palace.  The seed in question had no transition randomizer and no skips.

Per BadMagic's reading of the logic files (and I concur with the reading), the issue was the White_Palace_05[left1] transition:

```
  {
    "sceneName": "White_Palace_05",
    "gateName": "left1",
    "logic": "White_Palace_05[left1] | White_Palace_05[right1] + (FULLCLAW | WINGS) + FULLDASH",
    "oneWayType": "TwoWay",
    "Name": "White_Palace_05[left1]"
  },
```

A well-placed dash or wings (or possibly even airstall) allows taking the upper route in this room with no dash requirements, as seen in this clip: https://clips.twitch.tv/RelatedLitigiousDuckFUNgineer-Jc9KUhONnly2hI36

Per [Discord conversation](https://discord.com/channels/772964112908156938/822832351797182514/974895264924045393), it would probably make sense to add this as a skip under Precise Movement:

- Wings, Left Dash, or possibly an air stall?
- ~~Left~~**Right** claw is sufficient without wings (full claw isn't required)

So maybe logic like:

`"White_Palace_05[left1] | White_Palace_05[right1] + ((FULLCLAW | WINGS) + FULLDASH) | (PRECISEMOVEMENT + (RIGHTCLAW | WINGS) + (WINGS | LEFTDASH | AIRSTALL))"`

would be appropriate here?

**Comment by homothetyhk** [comment]
Closed by [2b98d47](https://github.com/homothetyhk/RandomizerMod/commit/2b98d47a91ff8612a65fd5af22b7c7fa9f71d575).
