### ISSUE TITLE
A way to adjust the overall cost of charm notches

### ISSUE THREAD

**Issue by argon932** [homothetyhk/RandomizerMod#15]
This is a feature request/suggestion.

Allow us to enter in a number or a difficulty setting for Charm Notch randomization. Right now it chooses a number then spreads that number out across all charms (to my knowledge). It'd be nice to have a setting Easy, Normal, Hard, Very Hard. That adjusts this number. Alternatively, let use set the range.

I was looking at the code and I tried to change this number but the dll would not compile with dnspy. My coding knowledge is extremely limited though.

**Comment by homothetyhk** [comment]
Closed by [ae8e8f5](https://github.com/homothetyhk/RandomizerMod/commit/ae8e8f5722f52b7d95db6501bbd6bab2ead90c37).
