### ISSUE TITLE
Error in logic - Helper log assumes I can use dive but I cannot gather soul 

### ISSUE THREAD

**Issue by oyasumi1290** [homothetyhk/RandomizerMod#16]
I may have found an error in the logic. I spawned in crystalized mound but now have no possible progression. I have picked up wings, dive, and grubsong but have no enemies and no environmental hazards to gather soul/take damage. 

The helper log seems to think I have dive so I have access to crystallized mound and resting ground catacombs when I have no way of gathering the soul to use it.

[settings.txt](https://github.com/homothetyhk/RandomizerMod/files/8864865/settings.txt)
[HelperLog.txt](https://github.com/homothetyhk/RandomizerMod/files/8864866/HelperLog.txt)

**Comment by flibber-hk** [comment]
If you warp to set start in benchwarp and wait for a few seconds, your soul will start to fill up (and you can carry this soul to the dive floor you want to break).

**Comment by oyasumi1290** [comment]
Huh I never knew benchwarp did that... Thanks for the tip!
