### ISSUE TITLE
Logic error - Is this a bug?

### ISSUE THREAD

**Issue by asimard1** [homothetyhk/RandomizerMod#19]
I got into Dirtmouth through very normal transitions and yet all transitions in Dirtmouth (and all those after that) are out of logic according to mapmod (and thus according to the randomizer too). There is no skip required to get to Dirtmouth at all, so I'm wondering why it's considered out of logic.

In the HelperLog, the problem can be seen clearly. I got to Dirtmouth through a transition that is in logic (no star), yet the one just after was out of logic...
![image](https://user-images.githubusercontent.com/58919185/184735503-c5485e5d-1e26-40d0-944c-0f345db698aa.png)

Here are some files that could be of interest.
[HelperLog.txt](https://github.com/homothetyhk/RandomizerMod/files/9340380/HelperLog.txt)
[settings.txt](https://github.com/homothetyhk/RandomizerMod/files/9340382/settings.txt)
[ModLog.txt](https://github.com/homothetyhk/RandomizerMod/files/9340383/ModLog.txt)

Let me know if any other files could help find the problem, I'm making a backup of my Team Cherry folder just in case.

**Comment by homothetyhk** [comment]
Fixed with [d9ae5ea](https://github.com/homothetyhk/RandomizerMod/commit/d9ae5ea48ade621821f6c325812e883f6be747be).
