### ISSUE TITLE
Version 4.0.9 does not have a Randomizer option when creating a new game

### ISSUE THREAD

**Issue by MrPokemon11** [homothetyhk/RandomizerMod#21]
I manually replaced my randomizer 4 mod folder with version 4.0.9 as, despite Scarab saying I was on 4.0.9, I was on 4.0.8. However, now that I have 4.0.9, I can not create a new randomizer game.  I do not want to switch between 4.0.9 and 4.0.8 every time I want to make a new game, so if this could be fixed that would be appreciated. I have also attached the ModLog.
[ModLog.txt](https://github.com/homothetyhk/RandomizerMod/files/9714923/ModLog.txt)
![wheresTheRando](https://user-images.githubusercontent.com/53610352/194041332-e836526d-fa19-4a19-926b-29fc6f7c34ec.jpg)

**Comment by homothetyhk** [comment]
By manually updating one mod, you did not update the rest of your mods. MenuChanger, ItemChanger, and perhaps others are out of date. Uninstalling and reinstalling randomizer through Scarab will properly update all mods.
