### ISSUE TITLE
Brooding Mawlek logic too optimistic for newer player

### ISSUE THREAD

**Issue by estelendur** [homothetyhk/RandomizerMod#22]
Hi! I am a newer Hollow Knight player and I've been playing some rando to have something to do while trying to git gud besides fight whichever boss I'm stuck on a hundred times.

Because I am not that great at the game, I have the skip level set to Casual/no skips. The logic assumes that I can do the spike pogo to get to Brooding Mawlek with no additional movement tech. For me this is not remotely true. Could it be changed to require Precise Movement?

**Comment by PancakeIdentity** [comment]
Spike pogos are extremely basic and are required with no skip logic in a lot of places. I recommend just practicing them, they are extremely useful in so many places.
