### ISSUE TITLE
Fungal Wastes check seemingly inaccessible?

### ISSUE THREAD

**Issue by estelendur** [homothetyhk/RandomizerMod#23]
The ceiling geo rock below Cornifer in I think it's Fungal2_18 falls onto a bouncy mushroom and I can't figure any way at all to retrieve it.

**Comment by Exempt-Medic** [comment]
Jumping/Falling onto it and mashing the UP button will work. You can also use Desolate Dive / Descending Dark, Steady Body, or a well-timed Nail Art, but mashing UP should do just fine

**Comment by estelendur** [comment]
thank you :) I feel silly now :D
