### ISSUE TITLE
Crystalized Mound logic is incorrect for skipless wings

### ISSUE THREAD

**Issue by PancakeIdentity** [homothetyhk/RandomizerMod#24]
The randomizer assumes you can do Crystalized Mound with just wings, however, there is a jump that requires claw. You could get around this with shade/enemy skips, but I have none of those checked and the game still assumes I can reach the end of this room. You also cannot pogo the crystals on the wall here, or if you can, it is extremely precise.
![Here is an image of the jump](https://user-images.githubusercontent.com/48536327/195466363-927d80f1-ebd5-4141-97a3-1eb3aadbffa0.jpg)

**Comment by flibber-hk** [comment]
You can pogo the crystals with QoL installed and enabled. QoL is a dependency for rando, which means that it should be installed by Scarab automatically. If not, make sure that you have it.

**Comment by homothetyhk** [comment]
Added OBSCURESKIPS in [a37b836](https://github.com/homothetyhk/RandomizerMod/commit/a37b836a960566259557d530c4e1476fd053dd4e).
