### ISSUE TITLE
Elevator Pass Not in Inventory When Picked Up

### ISSUE THREAD

**Issue by dastrdly6585** [homothetyhk/RandomizerMod#25]
With the newest release (version 4.1.0) the elevator pass no longer shows up in the inventory when picked up.  As a result, there is no direct in-game indication you have picked it up (elevator pass is not indicated by hovering over Focus).  In older versions (4.0.9 and earlier), there was an explicit elevator pass item alongside the other key items in your inventory to indicate you had it.

**Comment by homothetyhk** [comment]
This is not a RandomizerMod issue. But also, this is incorrect; there has never been an explicit elevator pass item added to the inventory by RandomizerMod or ItemChanger.

**Comment by dastrdly6585** [comment]
After downgrading the randomizer to the previous version, I have confirmed that I misremembered the elevator pass being in the inventory.  Sorry for the confusion.
