### ISSUE TITLE
Descnding Dark First Doesn't Unlock Dive Checks in Helper Log

### ISSUE THREAD

**Issue by dastrdly6585** [homothetyhk/RandomizerMod#26]
After collecting Descending Dark (which turned into Desolate Dive since it was the first dive pickup), the helper log does not indicate I have access to any checks which use Dive to access (e.g. Crystal Peaks, Resting Grounds crypts) even though I already have Mantis Claw and Mothwing Cloak which provides all other required movement to get to those checks.  This issue appears to have started in the latest version (v4.1.0).  I have attached the settings, spoiler log, helper log, tracker log, tracker data, tracker data without sequence breaks debug history, and ordered item progression spoiler log to help troubleshoot the issue (the json files have their extensions changed to txt to enable upload):

[settings.txt](https://github.com/homothetyhk/RandomizerMod/files/10453179/settings.txt)
[RawSpoiler.txt](https://github.com/homothetyhk/RandomizerMod/files/10453175/RawSpoiler.txt)
[HelperLog.txt](https://github.com/homothetyhk/RandomizerMod/files/10453178/HelperLog.txt)
[TrackerLog.txt](https://github.com/homothetyhk/RandomizerMod/files/10453187/TrackerLog.txt)
[TrackerData.txt](https://github.com/homothetyhk/RandomizerMod/files/10453174/TrackerData.txt)
[TrackerDataWithoutSequenceBreaksDebugHistory.txt](https://github.com/homothetyhk/RandomizerMod/files/10453183/TrackerDataWithoutSequenceBreaksDebugHistory.txt)
[OrderedItemProgressionSpoilerLog.txt](https://github.com/homothetyhk/RandomizerMod/files/10453168/OrderedItemProgressionSpoilerLog.txt)

Edit: Progressing further into the rando seed, I collected both other copies of dive and the helper log still didn't unlock the dive-specific checks.

**Comment by homothetyhk** [comment]
Fixed in [787c5ea](https://github.com/homothetyhk/RandomizerMod/commit/787c5eab02ef99a40173a90e028d8c7a04f27a43).
