### ISSUE TITLE
Dreamer Locations

### ISSUE THREAD

**Issue by BlueRedShark** [homothetyhk/RandomizerMod#29]
On my save of the randomizer, two of the dreamers were in the White Palace, one was randomised to the Pale King Kingsoul item, and the other is right at the end of the path of pain, I'm not sure if there is a setting to make this not happen, but this could prevent a person from beating the Hollow Knight. I don't know what can be done about this, but I am just pointing it out that key completion items can be in the Path of Pain.

**Comment by BlueRedShark** [comment]
Ok I just went to the black egg as I cant finish Path of Pain, and it opened but the herrah face, the one in PoP, stayed, like just a floating glowing herrah mask that is just there when the egg entrance is open

**Comment by homothetyhk** [comment]
There is a setting to not randomize items in Path of Pain: see [the readme](https://github.com/homothetyhk/RandomizerMod#long-location-settings) for more information.
