### ISSUE TITLE
bug that breaks the randomizer when using hollownest vocalized mod

### ISSUE THREAD

**Issue by xxx3lixxx** [homothetyhk/RandomizerMod#31]
after giving a delicate flower to the pale lurker in the hollownest vocalized mod it ends up reverting the randomizer settings and makes everything normal.

**Comment by homothetyhk** [comment]
This would be an issue for ItemChanger, not RandomizerMod. But in any case, if another gameplay mod makes incompatible changes with ItemChanger, it is unlikely to be fixed.
