### ISSUE TITLE
Add a "debug mode"

### ISSUE THREAD

**Issue by ShadiestGoat** [homothetyhk/RandomizerMod#35]
It would be nice to have an option that would dump all the logic, settings, etc into a file before randomization begins

**Comment by homothetyhk** [comment]
The randomizer produces the settings file by allowing connections to append to it after randomization. It isn't possible to produce the settings file before or during randomization, when connections settings may not be final.

It is possible to dump logic and base randomizer settings before randomization, but that doesn't seem broadly useful enough to ordinary users to belong in the base randomizer. I think it would make more sense to have a connection with fine-grained options for logging debug information (though, I'm not likely to work on such a mod any time soon).
