### ISSUE TITLE
Waterways_06 logic

### ISSUE THREAD

**Issue by muyjohno** [homothetyhk/RandomizerMod#37]
https://github.com/homothetyhk/RandomizerMod/blob/b7371941cc29404d3b3954df9c2591644760ad33/RandomizerMod/Resources/Logic/transitions.json#L3848C131-L3848C131

Hi. I was playing a room randomizer and was surprised to see that, relatively early, the logic believed I could leave Waterways_06 (the room normally to the left of the C-Dash spike tunnel from waterways to Isma's Grove) to the right (the Right1 exit that normally leads to the spike tunnel). I had access to the room from the Top1 entrance. I only had Shade Cloak and Isma's Tear; no vertical and no C-Dash. I had only basic no-skip logic enabled.

I checked the logic in the repo and it looks like it believes I can leave the Right1 exit with Isma's on its own. It seems like I would need Isma's and some vertical at least (maybe only wings, I'm not sure if claw would work) so I think the logic needs to be modified.

I'm not sure what the change would be exactly, but maybe changing `ACID` for `(ACID + WINGS)` or similar.

Thanks in advance for your help, and thanks for the randomizer!

**Comment by homothetyhk** [comment]
Actually, it is possible to jump normally off of the strange wall geometry near the right transition. I am sympathetic though to the idea that this might be to obscure for skipless logic, so I will consider changing it in the next release.

**Comment by muyjohno** [comment]
Oh I had no idea! I'll have to give that a try, then. I guess this is the kind of thing that might have a helper platform elsewhere? I'm thinking of e.g. the pogoable sign in the right side city hub that allows you to reach the upper left exit.

I'm happy with whatever change you decide on. Thanks for the reply and for looking at it.

**Comment by homothetyhk** [comment]
Resolved in [e6a832e](https://github.com/homothetyhk/RandomizerMod/commit/e6a832ed316e8b189189e86096ff8a012148c62d).
