### ISSUE TITLE
Logic Error in Waterways_07

### ISSUE THREAD

**Issue by glowstonetrees** [homothetyhk/RandomizerMod#38]
![Screenshot_2023-12-19_200111](https://github.com/homothetyhk/RandomizerMod/assets/154679733/84709014-eab1-433c-83e2-f34c756dcecf)

Coming from the Waterways_07[top1] transition, the [door1] transition can be reached by pogoing the object indicated in the image attached. i.e. absolutely no items are required, only background object pogo is required.

However, according to the Logic implies that wings is needed? (I'm not sure if I'm reading the logic correctly, but the Randomiser told me that I did a sequence break after I pogoed to that door)

"sceneName": "Waterways_07",
    "gateName": "door1",
    "logic": "Waterways_07[door1] | Waterways_07 + ANYCLAW | Waterways_07[top1] + WINGS | (Waterways_07 + ENEMYPOGOS + $SHRIEKPOGO[1,1,before:ROOMSOUL] | Waterways_07[right1]) + $SHRIEKPOGO[4]",
    "oneWayType": "TwoWay",
    "Name": "Waterways_07[door1]"

**Comment by homothetyhk** [comment]
Resolved in [e6a832e](https://github.com/homothetyhk/RandomizerMod/commit/e6a832ed316e8b189189e86096ff8a012148c62d).
