### ISSUE TITLE
Logic Error in Unbreakable_Strength

### ISSUE THREAD

**Issue by ftqeyza** [homothetyhk/RandomizerMod#45]
![6F(AZH%P7VFL7CO A$ ZKWI](https://github.com/homothetyhk/RandomizerMod/assets/173885722/6bd8747e-7daf-4da0-8a73-b057aa7046b0)
![K$PE( {FG2~8)0}~M`U(AJM](https://github.com/homothetyhk/RandomizerMod/assets/173885722/c6e5025d-bdc7-45a8-bc06-d19b66f307f1)

I get Grimmchild and Fragile Strength, and also get City Storerooms Stag to visit Lemm, but the Unbreakable_Strength is still out of logic until I get another Fragile Strength.

[settings.txt](https://github.com/user-attachments/files/15984226/settings.txt)
[HelperLog.txt](https://github.com/user-attachments/files/15984228/HelperLog.txt)

**Comment by homothetyhk** [comment]
This is not a logic error. The Unbreakable_Strength location is not reachable in logic unless you either have the ability to repair Fragile Strength or have Unbreakable Strength. Since this is a transition rando, it will not be appear in logic until you have found access to Leg Eater.
