### ISSUE TITLE
Rancid_Egg-Queen's_Gardens logic

### ISSUE THREAD

**Issue by micsthepick** [homothetyhk/RandomizerMod#54]
The only way in to Fungus3_34 I have currently is from the top, which means I need to either have the gate on the right open or to be able to penetrate the black barrier blocking the other way through, and the other paths to that room are all blocked off from inside?

**Comment by micsthepick** [comment]
looks like I need Cycle for a QoL lever skip? In which case that's not considered by the logic.

**Comment by micsthepick** [comment]
[user3.json.txt](https://github.com/user-attachments/files/18121956/user3.json.txt)
[user3.modded.json.txt](https://github.com/user-attachments/files/18121957/user3.modded.json.txt)
these are my profile json files (with the *archipelago* server hidden)

**Comment by BadMagic100** [comment]
No issue, player has qg stag + claw + wings to reach it from the left
